export type ShapeType =
  | 'rectangle'
  | 'triangle'
  | 'trapezoid'
  | 'chevron'
  | 'hexagon'
  | 'ellipse'
  | 'diamond'
  | 'parallelogram'
  | 'pentagon'
  | 'thick-arrow'
  | 'arrow'
  | 'diagonal-line'
  | 'line'
  | 'custom'
