import {
  ArrowUp,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  User,
  Users,
  Building,
  Factory,
  Briefcase,
  FileText,
  Folder,
  Database,
  ClipboardList,
  Server,
  Monitor,
  Smartphone,
  Mail,
  MessageSquare,
  Phone,
  CheckCircle,
  AlertTriangle,
  Info,
  Settings,
  Activity,
  BarChart,
  PieChart,
  TrendingUp,
  DollarSign,
  CreditCard,
  Truck,
  Package,
  MapPin,
  Clock,
  Calendar,
  Target,
  Shapes,
} from 'lucide-vue-next'

export const ICONS = {
  arrowUp: ArrowUp,
  arrowDown: ArrowDown,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  user: User,
  users: Users,
  building: Building,
  factory: Factory,
  briefcase: Briefcase,
  fileText: FileText,
  folder: Folder,
  database: Database,
  clipboardList: ClipboardList,
  server: Server,
  monitor: Monitor,
  smartphone: Smartphone,
  mail: Mail,
  messageSquare: MessageSquare,
  phone: Phone,
  checkCircle: CheckCircle,
  alertTriangle: AlertTriangle,
  info: Info,
  settings: Settings,
  activity: Activity,
  barChart: BarChart,
  pieChart: PieChart,
  trendingUp: TrendingUp,
  dollarSign: DollarSign,
  creditCard: CreditCard,
  truck: Truck,
  package: Package,
  mapPin: MapPin,
  clock: Clock,
  calendar: Calendar,
  target: Target,
}

export const ICON_CATEGORIES = {
  general: {
    label: 'General',
    icon: Shapes,
    icons: {
      arrowUp: ArrowUp,
      arrowDown: ArrowDown,
      arrowLeft: ArrowLeft,
      arrowRight: ArrowRight,
      checkCircle: CheckCircle,
      alertTriangle: AlertTriangle,
      info: Info,
      settings: Settings,
      target: Target,
    },
  },
  business: {
    label: 'Business',
    icon: Briefcase,
    icons: {
      user: User,
      users: Users,
      building: Building,
      factory: Factory,
      briefcase: Briefcase,
      fileText: FileText,
      folder: Folder,
      database: Database,
      clipboardList: ClipboardList,
      activity: Activity,
      barChart: BarChart,
      pieChart: PieChart,
      trendingUp: TrendingUp,
      dollarSign: DollarSign,
      creditCard: CreditCard,
    },
  },
  techLogistics: {
    label: 'Tech & Logistics',
    icon: Server,
    icons: {
      server: Server,
      monitor: Monitor,
      smartphone: Smartphone,
      mail: Mail,
      messageSquare: MessageSquare,
      phone: Phone,
      truck: Truck,
      package: Package,
      mapPin: MapPin,
      clock: Clock,
      calendar: Calendar,
    },
  },
}

export type IconType = keyof typeof ICONS
export type IconCategory = keyof typeof ICON_CATEGORIES
